config/routes.rb
Rails.application.routes.draw do

  resources :places, only: [:show, :edit]

  get 'ratings/index'
  get 'ratings/show'
  get 'ratings/new'
  get 'ratings/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events
  resources :messages, only: [:show]
  resources :imgs, only: [:show]
  resources :users, :tags
  root to: 'pages#home'
  get "/login", to: "sessions#login"
  post "/logged", to: "sessions#logged"
  delete "/logout", to: 'sessions#logout'
  post '/events/:id/attend', to: 'events#attend', as: "events_attend"

  patch '/messages/:id/content', to: 'messages#content', as: "content"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :places
    has_many :messages

    has_many :groups
    has_many :users, through: :groups

    has_many :eventtags
    has_many :tags, through: :eventtags
    
    accepts_nested_attributes_for :tags
    accepts_nested_attributes_for :groups
    accepts_nested_attributes_for :places
    accepts_nested_attributes_for :messages


    # def autosave_associated_records_for_tags
    #     if tag_exists = Tag.find_or_create_by(main_tag: tags[0].main_tag)
    #         Usertag.find_or_create_by(
    #             tag_id: tag_exists.id,
    #             user_id: self.id)
    #     end
    # end
end

app/models/eventtag.rb
class Eventtag < ApplicationRecord
    belongs_to :event
    belongs_to :tag
end

app/models/group.rb
class Group < ApplicationRecord
    belongs_to :user
    belongs_to :event
end

app/models/img.rb
class Img < ApplicationRecord
    belongs_to :event
end

app/models/message.rb
class Message < ApplicationRecord

    belongs_to :event
    
end

app/models/place.rb
class Place < ApplicationRecord
    belongs_to :event
end

app/models/rating.rb
class Rating < ApplicationRecord
    belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord

    has_many :usertags
    has_many :users, through: :usertags

    has_many :eventtags
    has_many :users, through: :usertags

    validates :main_tag, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :ratings

    has_many :groups
    has_many :events, through: :groups


    has_many :usertags, dependent: :destroy
    has_many :tags, through: :usertags

    has_secure_password
    accepts_nested_attributes_for :tags
    validates :name, presence: :true, uniqueness: :true

    def autosave_associated_records_for_tags
        if tag_exists = Tag.find_or_create_by(main_tag: tags[0].main_tag)
            Usertag.find_or_create_by(
                tag_id: tag_exists.id,
                user_id: self.id)
        end
    end

end

app/models/usertag.rb
class Usertag < ApplicationRecord
    belongs_to :user
    belongs_to :tag
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def new
    if @current_user
      @event = Event.new
      @event.tags.build
      @event.groups.build
      @event.messages.build
      @event.places.build
    else
      flash[:notice] = "Please sign in to continue!"
      redirect_to "/login"
    end
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      redirect_to event_path(@event)
    else
      flash[:errors] = @event.errors.full_messages
      flash[:data] = @event
      redirect_to "/events/new"
    end
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(event_params)
      redirect_to event_path(@event)
    else
      flash[:errors] = @event.errors.full_messages
      redirect_to edit_event_path(@event)
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to user_path(@current_user)
  end

  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @places = Place.find_by(event_id: @event.id)
    @groups = Group.find_by(event_id: @event.id)
    @message = Message.find_by(event_id: @event.id)
  end

  def attend
    @event = Event.find(params[:id])
    @group = Group.new(user_id: @current_user.id, event_id: @event.id, number: 0) 
    if @group.save  
      redirect_to event_path(@event)
    else
      flash[:errors] = @group.errors.full_messages
    end
  end

  private

  def event_params
    params.require(:event).permit(
      :name, 
      :time, 
      :loc, 
      tags_attributes: [:main_tag],
      messages_attributes: [:event_id, :title, :content],
      places_attributes: [:name, :latitude, :longitude, :event_id],
      groups_attributes: [:event_id, :user_id, :number]
      )
  end
end

app/controllers/imgs_controller.rb
class ImgsController < ApplicationController

    def show
        @img = Img.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @events = Event.all
    end
    
  end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def new
    flash[:data] ? @tag = Tag.new(flash[:data]) : @tag = Tag.new
  end

  def create
    user = User.find_by_name(@current_user.name)
    tag = Tag.new(get_params)
    if tag.save
      Usertag.create(user_id:user.id, tag_id:tag.id)
      redirect_to tag_path(tag)
    else
      flash[:errors] = tag.errors.full_messages
      flash[:data] = tag
      redirect_to new_tag_url
    end
  end

  def update
    tag = Tag.find(params[:id])
    if tag.update(get_params)
      redirect_to tag_path tag
    else
      flash[:errors] = tag.errors.full_messages
      redirect_to tags_edit
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def destroy
    Tag.find(params[:id]).delete
    redirect_to tags_path
  end

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
    @users = @tag.users
  end

  private

  def get_params
    params.require(:tag).permit(:main_tag)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    flash[:data] ? @user = User.new(flash[:data]) : @user = User.new
    @user.tags.build
  end

  def create
    user = User.new(get_params)
    if user.save
      session[:user_id] = user.id
      session[:profile] = %w(email dob loc)
      redirect_to user_path(user)
    else
      flash[:errors] = user.errors.full_messages
      flash[:data] = user
      redirect_to "/users/new"
    end
  end

  def destroy
    @user = User.find(params[:id])
    Usertag.where(user_id: "#{@user.id}").delete_all
    @user.delete
    session[:user_id] = nil
    redirect_to '/'
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @tags = @user.tags
    if @current_user
      @current_user.name == @user.name ? @wner = true : @wner = false
    else
      @wner = false
    end
    @events = @user.events
  end

  def edit
    @user = User.find(params[:id])
    @user.tags.build
  end

  def update
    user = User.find(params[:id])
    if user.update(get_params)
      if user.email == nil || user.email == ""
        session[:profile].delete('email')
      else
        session[:profile] << 'email' unless session[:profile].include?('email')
      end
      if user.dob == nil || user.dob == ""
        session[:profile].delete('dob')
      else
        session[:profile] << 'dob' unless session[:profile].include?('dob')
      end
      if user.loc == nil || user.loc == ""
        session[:profile].delete('loc')
      else
        session[:profile] << 'loc' unless session[:profile].include?('loc')
      end
      redirect_to user_path(user)
    else
      flash[:errors] = user.errors.full_messages
      redirect_to "/users/#{user.id}/edit"
    end
  end

  private

  def get_params
    params.require(:user).permit(
      :name,
      :email,
      :dob,
      :loc,
      :password,
      tags_attributes: [:main_tag])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/imgs_helper.rb
module ImgsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/edit.html.erb
<div class="ui internally grid">
    <div class="row">
        <div class="three wide column">
            <% if flash[:errors] %>
            <ul>
                <% flash[:errors].each do |error| %>
                <li>Error: <%= error %></li>
                <% end %>
            </ul>
            <% end %>
        </div>
        <div class="ten wide column">
            <div class="ui one column stackable center aligned page grid">
                <div class="column twelve wide">
                    <h1>Edit MeetUp</h1>
                </div>
            </div>
        </div>
        <div class="three wide column">
            <img>
        </div>
    </div>
    <div class="row">
        <div class="three wide column">
            <img>
        </div>
        <div class="ten wide column">
            <%= form_for @event, :html => {class: "ui form"} do |f|%>
            <div class="field">
                <label>Name for MeetUp:</label>
                <%= f.text_field :name,  placeholder: "Name" %>
            </div>
            <div class="field">
                <label>City:</label>
                <%= f.text_field :loc,  placeholder: "City" %>
            </div>
            <div class="field">
                <%= f.fields_for :groups do |x| %>
                <label>Max number of people for event:</label>
                <%= x.number_field :number, min: 2, max: 9 %>
                <%= x.hidden_field :event_id, value: @event.id %>
                <%= x.hidden_field :user_id, value: @current_user.id %>
                <% end %>
            </div>
            <div class="field">
                <%= f.fields_for :tags do |y| %>
                <label>Insert tag for your event:</label>
                <%= y.text_field :main_tag %>
                <% end %>
            </div>
            <div class="field">
                <label>Set a date and time for MeetUp:</label>
                <%= f.datetime_select(:time, selected: Date.today, start_year: Date.today.year) %>
            </div>
            <div class="field">
                <%= f.fields_for :places do |z| %>
                <div class="ui one column stackable center aligned page grid">
                    <div class="column twelve wide">
                        <h3>GoogleMap Details </h3>
                    </div>
                </div>
                <%= z.label 'Location Name:' %>
                <%= z.text_field :name %>

                <%= z.label :latitude %>
                <%= z.text_field :latitude %>

                <%= z.label :longitude %>
                <%= z.text_field :longitude %>

                <%= z.hidden_field :event_id, value: @event.id %>

                <% end %>
            </div>

            <br>
            <div class="ui one column stackable center aligned page grid">
                <div class="column twelve wide">
                    <button class="ui button" type="submit">Submit</button>
                </div>
            </div>
            <% end %>
            </form>
        </div>
        <div class="three wide column">
            <img>
        </div>
    </div>
</div>

app/views/events/index.html.erb
<h1>Events</h1>

<% @events.each do |event| %>
<h4><%= link_to event.name, event_path(event) %></h4>

<% end %>

app/views/events/new.html.erb
<div class="ui internally grid">
    <div class="row">
        <div class="three wide column">
            <% if flash[:errors] %>
            <ul>
                <% flash[:errors].each do |error| %>
                <li>Error: <%= error %></li>
                <% end %>
            </ul>
            <% end %>
        </div>
        <div class="ten wide column">
            <div class="ui one column stackable center aligned page grid">
                <div class="column twelve wide">
                    <h1>New MeetUp</h1>
                </div>
            </div>
        </div>
        <div class="three wide column">
            <img>
        </div>
    </div>
    <div class="row">
        <div class="three wide column">
            <img>
        </div>
        <div class="ten wide column">
            <%= form_for @event, :html => {class: "ui form"} do |f|%>
                <%= f.fields_for :messages do |a| %>
                <%= a.hidden_field :event_id, value: @event.id %>
                <%= a.hidden_field :title, value: @event.name %>
                <%= a.hidden_field :content, value: @event.name %>
                <% end %>
                <div class="field">
                    <label>Name for MeetUp:</label>
                    <%= f.text_field :name,  placeholder: "Name" %>
                </div>
                <div class="field">
                    <label>City:</label>
                    <%= f.text_field :loc,  placeholder: "City" %>
                </div>
                <div class="field">
                    <%= f.fields_for :groups do |x| %>
                        <label>Max number of people for event:</label>
                        <%= x.number_field :number, min: 2, max: 9 %>
                        <%= x.hidden_field :event_id, value: @event.id %>
                        <%= x.hidden_field :user_id, value: @current_user.id %>
                    <% end %>
                </div>
                <div class="field">
                    <%= f.fields_for :tags do |y| %>
                    <label>Insert tag for your event:</label>
                    <%= y.text_field :main_tag %>
                    <% end %>
                </div>
                <div class="field">
                    <label>Set a date and time for MeetUp:</label>
                    <%= f.datetime_select(:time, selected: Date.today, start_year: Date.today.year) %>
                </div>
                <div class="field">
                    <%= f.fields_for :places do |z| %>
                    <div class="ui one column stackable center aligned page grid">
                        <div class="column twelve wide">
                            <h3>GoogleMap Details </h3>
                        </div>
                    </div>
                    <%= z.label 'Location Name:' %>
                    <%= z.text_field :name %>

                    <%= z.label :latitude %>
                    <%= z.text_field :latitude %>

                    <%= z.label :longitude %>
                    <%= z.text_field :longitude %>

                    <%= z.hidden_field :event_id, value: @event.id %>

                    <% end %>
                </div>

                <br>
                <div class="ui one column stackable center aligned page grid">
                    <div class="column twelve wide">
                        <button class="ui button" type="submit">Submit</button>
                    </div>
                </div>
                <% end %>
            </form>
        </div>
        <div class="three wide column">
            <img>
        </div>
    </div>
</div>

app/views/events/show.html.erb
<br>
<div class="ui three column divided grid">
        <div class="stretched row">
          <div class="column">
            <div class="ui segment">
                <h2><%=@event.name%></h2>
                <h4>
                    MeetUp Attendees:
                    <% @event.users.each do |user| %>
                        <br>
                        <%= link_to user.name, user_path(user.id) %>
                        <br>
                    <% end %>
                </h4>
            </div>
          </div>
          <div class="column">
            <div class="ui segment">
                <h2><%= @event.time.strftime('%B %d, %Y at %H:%M') %></h2>
            </div>
            <div class="ui segment">
                <h2> City: <%= @event.loc %> </h2>              
            </div>
          </div>
          <div class="column">
            <div class="ui segment">
                <p>Max People: <%= @groups.number %></p>
            </div>
            <div class="ui segment">
                <p>People Attending: <%= @event.users.count %></p>  
            </div>            
            <div class="ui segment">
                <% if @event.users.include?(@current_user) %>
                    <h4>You're attending this MeetUp</h4>
                <% elsif @groups.number > @event.users.count %>
                    <%= link_to 'Attend Event', events_attend_path(@event), method: :post %>
                <% else %>
                    <h4>You've missed the window to MeetUp</h4>
                <% end %>
            </div>
          </div>
        </div>
      </div>
    <br>
<br>

<% begin %>
    <%= link_to 'Google Location', place_path(@places) %> |
    <%= link_to 'Group messages', message_path(@message)%> |
    <%= link_to 'Edit MeetUp', edit_event_path(@event) %> |
    <%= link_to 'Delete MeetUp', event_path(@event), method: :delete %>
<% rescue %>
<% end %>

app/views/imgs/show.html.erb
<h1>Imgs#show</h1>
<p>Find me in app/views/imgs/show.html.erb</p>

app/views/tags/_tags_form.html.erb
<div>
   <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
         <div><%= error %></div>
      <% end %>
   <% end %>
</div>
<div>
   <%= form_for @tag do |f| %>
   <div>
      <%= f.label :main_tag, 'Tag' %>
      <%= f.text_field :main_tag %>
   </div>
      <%= f.submit 'Done' %>
   <% end %>
</div>

app/views/tags/edit.html.erb
<h1>Tags#edit</h1>
<%= render 'tags_form' %>

app/views/tags/index.html.erb
<h1>Tags#index</h1>

<% @tags.each do |tag| %>
<h4><%= link_to tag.main_tag, tag_path(tag) %></h4>
<% end %>
<%= link_to 'new tag', 'tags/new' %>

app/views/tags/new.html.erb
<%= render 'tags_form' %>

app/views/tags/show.html.erb
<h1><%=@tag.main_tag%></h1>
<h4>Sharing your interest:</h4>
<div>
   <% @users.each do |user| %>
   <ul><li> 
      <%= link_to user.name, user_path(user) %>
   </li></ul>
   <% end %>
</div>
<%= link_to 'tags', tags_path%>
<%= link_to 'delete', tag_path(@tag), method: :delete %>
<%= link_to 'edit', "#{tag_path(@tag)}/edit" %>

app/views/users/_users_form.html.erb
<div>
   <% if flash[:errors] %>
      <% flash[:errors].each do |error| %>
         <div><%= error %></div>
      <% end %>
   <% end %>
</div>



<%= form_for @user do |f| %>
<div class="ui very large form">
   <div class="six fields">

      <div class="field">
         <%= f.label :name, 'User'%>
         <%= f.text_field :name%>
      </div>
      <div class="field">
         <%= f.label 'Password:' %>
         <%= f.password_field :password %>
      </div>

      <% if @current_user %>
         <div class="field">
            <%= f.label 'Email:' %>
            <%= f.email_field :email %>
         </div>
         <div class="field">
            <%= f.label 'DOB' %>
            <%= f.number_field :dob %>
         </div>
         <div class="field">
            <%= f.label 'City:' %>
            <%= f.text_field :loc %>
         </div>
      <% end %>

      <% if !@current_user %>
         <%= f.fields_for :tags do |t| %>
            <div class="field">
               <%= t.label :main_tag, 'Tag your interests' %>
               <%= t.text_field :main_tag %>
            </div>
            <%= t.hidden_field :user_id, value: @user.id %>
         <% end %>
      <% end %>

   <%= f.submit 'Submit', class:"ui submit button" %>
   </div>
</div>
<% end %>

app/views/users/edit.html.erb
<%= render 'users_form' %>

app/views/users/index.html.erb
<h1>Users#index</h1>

<% @users.each do |user| %>
<h4><%= link_to user.name, user_path(user) %></h4>
<% end %>

app/views/users/new.html.erb
<h2>Your profile</h2>
<%= render 'users_form' %>

app/views/users/show.html.erb
<br />
<div class="ui three column stackable very relaxed center aligned grid">
 <div class="stretched row">
    <div class="five wide blue column">
      <h2>You're going</h2>
      <div class="ui segment">
         <%if @events.empty?%>
            <p class="tag_status">No events, wanna<%= link_to ' tag ', new_tag_path %>more interests?</p>
         <%else%>
            <% @events.each do |event| %>
               <h4><%= link_to event.name, event_path(event) %></h4>
            <% end %>
         <% end %>
      </div>
    </div>
    <div class="five wide column">
      <h2>MeetUps nearby</h2>
      <div class="ui segment">
         <%begin%>
            <%Event.all.each do |event|%>
               <%if event.loc.downcase.include?(@user.loc.downcase)%>
                  <% unless @events.map(&:name).include?(event.name)%>
                     <%= @wner ? link_to(event.name, event_path(event)) : 'privacy by default'%>
                  <%end%>
               <%end%>
            <%end%>
         <%rescue StandardError => e%>
            <p>Add your <%= link_to "location", edit_user_path %> to find some</p>
         <%end%>
      </div>
    </div>
    <div class="three wide column">
      <h2>Your tags</h2>
      <div class="ui segment">
         <% @tags.each do |tag| %>
            <h4><%= link_to tag.main_tag, tag_path(tag) %></h4>
         <% end  %>
      </div>
    </div>
  </div>
</div>
<br />
<br />
<br />
<div>
   <%= @wner ? link_to('Edit',edit_user_path) : 'privacy by default'%> |
   <%= @wner ? link_to('Remove','/users/destroy', method: :delete) : 'privacy by default' %> |
    <% if @user.email != nil && @user.email != ""  %>
            email: <%=@wner ? @user.email : 'privacy by default'%> |
         <% end %>
         <% if @user.dob != nil && @user.dob != "" %>
            dob: <%=@wner ? @user.dob : 'privacy by default'%> |
         <% end %>
         <% if @user.loc != nil && @user.loc != ""%>
            city: <%=@wner ? @user.loc : 'privacy by default'%>
         <% end %>
</div>

<style>
   .tag_status {
    color: black;
   }
   .link_to {
      color: blue
   }
 </style>



<!-- <%= link_to 'users', users_path%> -->
<!-- <%= button_to 'Create a Event', new_event_path, {method: :get, data: @user.id} %> -->