config/routes.rb
Rails.application.routes.draw do

  resources :places, only: [:show, :edit]

  get 'ratings/index'
  get 'ratings/show'
  get 'ratings/new'
  get 'ratings/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events
  resources :messages, only: [:show]
  resources :imgs, only: [:show]
  resources :users, :tags
  root to: 'pages#home'
  get "/login", to: "sessions#login"
  post "/logged", to: "sessions#logged"
  delete "/logout", to: 'sessions#logout'
  post '/events/:id/attend', to: 'events#attend', as: "events_attend"

  patch '/messages/:id/content', to: 'messages#content', as: "content"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :places
    has_many :messages

    has_many :groups
    has_many :users, through: :groups

    has_many :eventtags
    has_many :tags, through: :eventtags
    
    accepts_nested_attributes_for :tags
    accepts_nested_attributes_for :groups
    accepts_nested_attributes_for :places
    accepts_nested_attributes_for :messages


    # def autosave_associated_records_for_tags
    #     if tag_exists = Tag.find_or_create_by(main_tag: tags[0].main_tag)
    #         Usertag.find_or_create_by(
    #             tag_id: tag_exists.id,
    #             user_id: self.id)
    #     end
    # end
end

app/models/eventtag.rb
class Eventtag < ApplicationRecord
    belongs_to :event
    belongs_to :tag
end

app/models/group.rb
class Group < ApplicationRecord
    belongs_to :user
    belongs_to :event
end

app/models/img.rb
class Img < ApplicationRecord
    belongs_to :event
end

app/models/message.rb
class Message < ApplicationRecord

    belongs_to :event
    
end

app/models/place.rb
class Place < ApplicationRecord
    belongs_to :event
end

app/models/rating.rb
class Rating < ApplicationRecord
    belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord

    has_many :usertags
    has_many :users, through: :usertags

    has_many :eventtags
    has_many :users, through: :usertags

    validates :main_tag, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :ratings

    has_many :groups
    has_many :events, through: :groups


    has_many :usertags, dependent: :destroy
    has_many :tags, through: :usertags

    has_secure_password
    accepts_nested_attributes_for :tags
    validates :name, presence: :true, uniqueness: :true

    def autosave_associated_records_for_tags
        if tag_exists = Tag.find_or_create_by(main_tag: tags[0].main_tag)
            Usertag.find_or_create_by(
                tag_id: tag_exists.id,
                user_id: self.id)
        end
    end

end

app/models/usertag.rb
class Usertag < ApplicationRecord
    belongs_to :user
    belongs_to :tag
end

app/controllers/imgs_controller.rb
class ImgsController < ApplicationController

    def show
        @img = Img.find(params[:id])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @events = Event.all
    end
    
  end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
    @place = Place.find(params[:id])
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)
xk
    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :latitude, :longitude, :event_id)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def new
    flash[:data] ? @tag = Tag.new(flash[:data]) : @tag = Tag.new
  end

  def create
    user = User.find_by_name(@current_user.name)
    tag = Tag.new(get_params)
    if tag.save
      Usertag.create(user_id:user.id, tag_id:tag.id)
      redirect_to tag_path(tag)
    else
      flash[:errors] = tag.errors.full_messages
      flash[:data] = tag
      redirect_to new_tag_url
    end
  end

  def update
    tag = Tag.find(params[:id])
    if tag.update(get_params)
      redirect_to tag_path tag
    else
      flash[:errors] = tag.errors.full_messages
      redirect_to tags_edit
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def destroy
    Tag.find(params[:id]).delete
    redirect_to tags_path
  end

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
    @users = @tag.users
  end

  private

  def get_params
    params.require(:tag).permit(:main_tag)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    flash[:data] ? @user = User.new(flash[:data]) : @user = User.new
    @user.tags.build
  end

  def create
    user = User.new(get_params)
    if user.save
      session[:user_id] = user.id
      session[:profile] = %w(email dob loc)
      redirect_to user_path(user)
    else
      flash[:errors] = user.errors.full_messages
      flash[:data] = user
      redirect_to "/users/new"
    end
  end

  def destroy
    @user = User.find(params[:id])
    Usertag.where(user_id: "#{@user.id}").delete_all
    @user.delete
    session[:user_id] = nil
    redirect_to '/'
  end

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @tags = @user.tags
    if @current_user
      @current_user.name == @user.name ? @wner = true : @wner = false
    else
      @wner = false
    end
    @events = @user.events
  end

  def edit
    @user = User.find(params[:id])
    @user.tags.build
  end

  def update
    user = User.find(params[:id])
    if user.update(get_params)
      if user.email == nil || user.email == ""
        session[:profile].delete('email')
      else
        session[:profile] << 'email' unless session[:profile].include?('email')
      end
      if user.dob == nil || user.dob == ""
        session[:profile].delete('dob')
      else
        session[:profile] << 'dob' unless session[:profile].include?('dob')
      end
      if user.loc == nil || user.loc == ""
        session[:profile].delete('loc')
      else
        session[:profile] << 'loc' unless session[:profile].include?('loc')
      end
      redirect_to user_path(user)
    else
      flash[:errors] = user.errors.full_messages
      redirect_to "/users/#{user.id}/edit"
    end
  end

  private

  def get_params
    params.require(:user).permit(
      :name,
      :email,
      :dob,
      :loc,
      :password,
      tags_attributes: [:main_tag])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/imgs_helper.rb
module ImgsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/places/_form.html.erb
<%= form_with(model: place, local: true) do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Places</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td><%= place.latitude %></td>
        <td><%= place.longitude %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<h2>Event: <%= @place.event.name%></h2>


<p>
  <strong>Location Name:</strong>
  <%= @place.name %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @place.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @place.longitude %>
</p>

<p>
  <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=17&size=400x300&markers=size:small%7Ccolor:red%7C#{@place.latitude},#{@place.longitude}&key=#{Rails.application.credentials.google_maps_api_key}", alt: "Map" %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Event Page', event_path(@place.event_id) %>