config/routes.rb
Rails.application.routes.draw do

  resources :places, only: [:show, :edit]

  get 'ratings/index'
  get 'ratings/show'
  get 'ratings/new'
  get 'ratings/create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :events
  resources :messages, only: [:show]
  resources :imgs, only: [:show]
  resources :users, :tags
  root to: 'pages#home'
  get "/login", to: "sessions#login"
  post "/logged", to: "sessions#logged"
  delete "/logout", to: 'sessions#logout'
  post '/events/:id/attend', to: 'events#attend', as: "events_attend"

  patch '/messages/:id/content', to: 'messages#content', as: "content"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    has_many :places
    has_many :messages

    has_many :groups
    has_many :users, through: :groups

    has_many :eventtags
    has_many :tags, through: :eventtags
    
    accepts_nested_attributes_for :tags
    accepts_nested_attributes_for :groups
    accepts_nested_attributes_for :places
    accepts_nested_attributes_for :messages


    # def autosave_associated_records_for_tags
    #     if tag_exists = Tag.find_or_create_by(main_tag: tags[0].main_tag)
    #         Usertag.find_or_create_by(
    #             tag_id: tag_exists.id,
    #             user_id: self.id)
    #     end
    # end
end

app/models/eventtag.rb
class Eventtag < ApplicationRecord
    belongs_to :event
    belongs_to :tag
end

app/models/group.rb
class Group < ApplicationRecord
    belongs_to :user
    belongs_to :event
end

app/models/img.rb
class Img < ApplicationRecord
    belongs_to :event
end

app/models/message.rb
class Message < ApplicationRecord

    belongs_to :event
    
end

app/models/place.rb
class Place < ApplicationRecord
    belongs_to :event
end

app/models/rating.rb
class Rating < ApplicationRecord
    belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord

    has_many :usertags
    has_many :users, through: :usertags

    has_many :eventtags
    has_many :users, through: :usertags

    validates :main_tag, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :ratings

    has_many :groups
    has_many :events, through: :groups


    has_many :usertags, dependent: :destroy
    has_many :tags, through: :usertags

    has_secure_password
    accepts_nested_attributes_for :tags
    validates :name, presence: :true, uniqueness: :true

    def autosave_associated_records_for_tags
        if tag_exists = Tag.find_or_create_by(main_tag: tags[0].main_tag)
            Usertag.find_or_create_by(
                tag_id: tag_exists.id,
                user_id: self.id)
        end
    end

end

app/models/usertag.rb
class Usertag < ApplicationRecord
    belongs_to :user
    belongs_to :tag
end

app/controllers/imgs_controller.rb
class ImgsController < ApplicationController

    def show
        @img = Img.find(params[:id])
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def new
    flash[:data] ? @tag = Tag.new(flash[:data]) : @tag = Tag.new
  end

  def create
    user = User.find_by_name(@current_user.name)
    tag = Tag.new(get_params)
    if tag.save
      Usertag.create(user_id:user.id, tag_id:tag.id)
      redirect_to tag_path(tag)
    else
      flash[:errors] = tag.errors.full_messages
      flash[:data] = tag
      redirect_to new_tag_url
    end
  end

  def update
    tag = Tag.find(params[:id])
    if tag.update(get_params)
      redirect_to tag_path tag
    else
      flash[:errors] = tag.errors.full_messages
      redirect_to tags_edit
    end
  end

  def edit
    @tag = Tag.find(params[:id])
  end

  def destroy
    Tag.find(params[:id]).delete
    redirect_to tags_path
  end

  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
    @users = @tag.users
  end

  private

  def get_params
    params.require(:tag).permit(:main_tag)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/imgs_helper.rb
module ImgsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meetup</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', 'https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css'%>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js'%>
  </head>

  <body>

      <div class="ui secondary  menu">
        <%= @current_user ?
          link_to('MeetUp', new_event_path, {class:"active item"}) :
          link_to('MeetUp', '/', {class:"active item"})
        %>
        <% if @current_user %>
          <% if session[:profile].count < 3 %>
            <%= link_to '!!', edit_user_path(@current_user), {class:"item"} %>
          <% end %>
          <%= link_to @current_user.name, user_path(@current_user), {class:"item"} %>
        <% elsif request.fullpath != "/users/new" %>
          <%= link_to 'New User', '/users/new', {class:"item"} %>
        <% end %>
        <div class="right menu">
          <div class="item">
            <div class="ui icon input">
              <input type="text" placeholder="Search...">
              <i class="search link icon"></i>
            </div>
          </div>
          <% if @current_user %>
          <%= link_to 'Logout', '/logout', {method: :delete, class:"ui item"} %>
          <% end %>
        </div>
      </div>


      <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<br />
<div class="ui one column stackable very relaxed center aligned grid">
 <div class="stretched row">

    <div class="ten wide column">
      <div class="ui segment">
        <% if !@curremnt_user %>
          <%= render 'sessions/login_form' %>
        <% end %>
      </div>
    </div>

  </div>
</div>
<br />